### ISSUE TITLE
GPU Usage Jetson Nano

### ISSUE THREAD

**Issue by corgan2222** [domcross/home_surveillance#1]
Does your fork support GPU Usage on the Jetson Nano, or is this build CPU based?
I tryed some other scripts, but without GPU the Nano can only handle FACE REC on one camera.

btw: do you have some instruction or install script for the needed dependencies?

**Comment by domcross** [comment]
Yes, Jetson Nano GPU is supported - in fact that is the main reason for my fork.

I only have one camera at hand so I can not comment on multiple camera scenarios. What I did successfully was adding the same RTSP resource multiple times - this worked, frame rates go down, though.

Dependencies:
You need to install (in most cases this means download and make/build manually):
- [Dlib 19.19](https://github.com/davisking/dlib.git) (clone repo, cd into it, then `python3 setup.py install --set DLIB_USE_CUDA=1`)
- PyTorch 1.4 ([wheel](https://forums.developer.nvidia.com/t/pytorch-for-jetson-nano-version-1-5-0-now-available/72048) from Nvidia)
- OpenCV 4.2.0 ([build script](https://github.com/mdegans/nano_build_opencv) by mdegans)
- [Openface](https://github.com/cmusatyalab/openface) (clone repo, cd into it, then `python3 setup.py install`)

There might be some more dependencies that need to be installed by apt-get or pip - see [Dockerfile](https://github.com/domcross/home_surveillance/blob/master/Dockerfile) and [requirements.txt](https://github.com/domcross/home_surveillance/blob/master/requirements.txt)

**Comment by corgan2222** [comment]
thanks! i will try to get this running.

**Comment by corgan2222** [comment]
After endless hours i managed to install everything.
But i get a error
`ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory`

I have cuda-10.2 installed and cant find a way to download/downgrade to cuda 10.0 without making a new SD Card Image.
Do you have an Idea how to downgrade to cuda 10.0?

**Comment by domcross** [comment]
Sounds like you already have upgrade your Jetson Nano to JetPack 4.4DP? Did you choose the Pytorch wheel for JP4.4?

Chances are that old CUDA-10.0 is still there, check your `/usr/local` folder if it looks like:
```
lrwxrwxrwx  1 root root ...  cuda -> cuda-10.2/
drwxr-xr-x 12 root root ... cuda-10.0/
drwxr-xr-x 12 root root ... cuda-10.2/
```
Changing the symbolic link `cuda` from `cuda-10.2` to `cuda-10.0` could be worth a try, but you must check your PATH environment variable as well for references to cuda-10.2 and change that accordingly.

You might want to check https://forums.developer.nvidia.com/t/jetpack-4-4-developer-preview-l4t-r32-4-2-released/120594 and other threads in the Nvidia-forums as well

**Comment by corgan2222** [comment]
I just bought the Nano 2 weeks ago and installed the latest JP4.4. So i only have Cuda 10.2 on the system. Seems i have to reinstall from scratch..

As its not really clear to me, wich Cuda version Version is shipped in wich JP Version (https://developer.nvidia.com/embedded/jetpack-archive ), can you tell me, wich Jetpack Version do you use (wich include Cuda 10.0)?

**Comment by domcross** [comment]
As far as I know JetPack 4.0 to 4.3 support CUDA 10.0.
I have JetPack 4.3 on my Nano.

**Comment by corgan2222** [comment]
After a fresh Installation with JP 4.3 and hours of compiling OpenCV i got it running. 

With one IP Camera mounted at the front door, i got 17fps with face-rec and around 17fps (25 comes from cam). But i cant test the face-rec itself, because the camera is mounted.

With my second IP test camera i can only run motion detection. On Face-rec i got OpenCV errors.

Should i write detailed bug reports about here?

**Comment by domcross** [comment]
Thanks for taking the journey and congratulations for succeeding.

Why can you not test face-rec? For training you can use photos from any source as long as the photo has only one person on it.

For the OpenCV errors with second camera please open another issue.

**Comment by domcross** [comment]
Closing for now as there was no more update for three months.
